catchup    = false
state_path = "state.db"

[rpc]
network = "Testnet"

[protocol]
genesis = "6pD4xDH3kRSyBdEacErHF7WTeJ2fUXmzU8zXHHTrCnHY"

[succinct]
api_key          = ""
contract_address = "0x0000000000000000000000000000000000000000"
eth_rpc_url      = "https://gateway.tenderly.co/public/sepolia"
version          = "latest"
