catchup    = true
host       = "0.0.0.0:3030"
state_path = "state.db"

[protocol]
genesis = "6pD4xDH3kRSyBdEacErHF7WTeJ2fUXmzU8zXHHTrCnHY"

[rpc]
network = "Testnet"

[succinct]
contract_address = "0x73876e41ca149853160Ed5BFeC22e3C7bABEA67a"
eth_rpc_url      = "https://gateway.tenderly.co/public/sepolia"
version          = "v0.0.4-rc.1"
