[profile.default]
fs_permissions = [ { access = "read", path = "./broadcast" } ]
libs           = [ "lib" ]
out            = "out"
remappings     = [ "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts" ]
src            = "src"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
