[package]
edition.workspace = true
license.workspace = true
name              = "nearx-orchestrator"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace            = true
config.workspace            = true
ethers                      = { version = "2.0" }
jsonrpsee                   = { version = "0.22.1", features = [ "server", "macros" ] }
jsonrpsee-core              = "=0.22.1"
log.workspace               = true
pretty_env_logger.workspace = true
reqwest-middleware          = "*"
reqwest-retry               = "*"
reqwest.workspace           = true
serde.workspace             = true
serde_json.workspace        = true
thiserror.workspace         = true
tokio.workspace             = true

near-light-client-protocol.workspace = true
near-light-client-rpc.workspace      = true
plonky2x                             = { git = "https://github.com/succinctlabs/succinctx.git" }

[dev-dependencies]
hex.workspace = true
