[package]
edition.workspace = true
license.workspace = true
name              = "near-light-client-succinct-operator"
version.workspace = true

[[bin]]
name              = "sync"
path              = "src/main.rs"
required-features = [ "sync" ]

[[bin]]
name              = "verify"
path              = "src/main.rs"
required-features = [ "verify" ]

[dependencies]
cfg-if                       = "1.0.0"
near-light-clientx.workspace = true

[features]
default = [ "testnet" ]
mainnet = [  ]
sync    = [  ]
testnet = [  ]
verify  = [  ]
