[package]
edition.workspace = true
license.workspace = true
name              = "near-light-client-succint-operator"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name              = "sync"
path              = "src/main.rs"
required-features = [ "sync" ]

[[bin]]
name              = "verify"
path              = "src/main.rs"
required-features = [ "verify" ]

[dependencies]
cfg-if                       = "*"
near-light-clientx.workspace = true

[features]
default = [  ]
sync    = [  ]
verify  = [  ]
