[profile.default]
fs_permissions = [ { access = "read", path = "./broadcast" } ]
libs           = [ "lib" ]
optimizer      = true
optimizer-runs = 1_000_000
out            = "out"
remappings     = [ "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts" ]
src            = "src"
