name: "Audit depdencies"

# Midnight each day
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  security_audit:
    name: "Security audit"
    runs-on: 
      group: ubuntu-22.04-8core
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

