name: "Check PR is ready for merge"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: "Lint"
    runs-on:
      group: ubuntu-22.04-8core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          cache-workspaces: |-
            .
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1

  test-rust:
    name: "Test Rust"
    runs-on:
      group: ubuntu-22.04-32core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          cache-workspaces: |-
            .
      - name: "Install cargo-nextest"
        run: cargo install cargo-nextest
      - name: "Run tests"
        run: cargo nextest run --workspace --locked --no-fail-fast

  test-beefy-proofs:
    name: "Test Beefy Proofs"
    runs-on:
      group: ubuntu-22.04-32core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          cache-workspaces: |-
            .
      - name: "Install cargo-nextest"
        run: cargo install cargo-nextest
      - name: "Run tests"
        run: cargo nextest run --workspace --locked --no-fail-fast 

  test-solidity-contracts:
    name: "Test Solidity Contracts"
    runs-on:
      group: ubuntu-22.04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          cache-workspaces: |-
            .
      - name: "Install forge"
        run: cargo install --git https://github.com/foundry-rs/foundry --bins --locked anvil cast chisel forge
      - name: "Run tests"
        run: cd nearx/contract && forge test -vv
