name: "Check PR is ready for merge"

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: "Lint"
    runs-on:
      group: ubuntu-22.04-8core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: "Check rust format"
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  test-rust:
    name: "Test Rust"
    runs-on:
      group: ubuntu-22.04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: "Install cargo-nextest"
        run: cargo install cargo-nextest
      - name: "Run tests"
        run: cargo nextest run --workspace --locked

