name: "Check PR is ready for merge"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: "Lint"
    runs-on:
      group: ubuntu-22.04-8core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          cache-workspaces: |-
            .
      - uses: actions-rust-lang/rustfmt@v1
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features          

  test-rust:
    name: "Test Rust"
    runs-on:
      group: ubuntu-22.04-32core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          cache-workspaces: |-
            .
      - name: "Install cargo-nextest"
        run: cargo install cargo-nextest
      - name: "Run tests"
        run: cargo nextest run --workspace --locked --no-fail-fast

  test-beefy-proofs:
    name: "Test Beefy Proofs"
    runs-on:
      group: ubuntu-22.04-32core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          cache-workspaces: |-
            .
      - name: "Install cargo-nextest"
        run: cargo install cargo-nextest
      - name: "Run beefy tests"
        run: cargo nextest run --workspace --locked --run-ignored ignored-only --no-fail-fast 

  test-solidity-contracts:
    name: "Test Solidity Contracts"
    runs-on:
      group: ubuntu-22.04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8.0
        with:
          cache-workspaces: |-
            .
      - name: "Install Foundry"
        uses: taiki-e/cache-cargo-install-action@v1
        with:
          git: https://github.com/foundry-rs/foundry
          tool: forge
          rev: 6ee3e88d2a48c7df48c85986e67f73cd2e6403d8
      - name: "Forge install"
        run: cd nearx/contract && forge install
      - name: "Run tests"
        run: cd nearx/contract && forge test -vv
